<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>AxisAndAlliesBattleSimulator</PackageId>
        <Version>1.0.1</Version>
        <Authors>Kostas Tsionis</Authors>
        <RepositoryUrl>https://github.com/kontsio1/Blame-the-Dice-not-the-Strat</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Description>A utility library for calculating axis and allies board game battle outcomes</Description>
        <PackageReleaseNotes>Corrected project naming</PackageReleaseNotes>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <None Include="LICENSE" Pack="true" PackagePath="\" />
    </ItemGroup>

    <PropertyGroup>
        <RootNamespace>axis_console_project</RootNamespace>
        <InternalsVisibleTo>axis_console_project.Tests</InternalsVisibleTo>
    </PropertyGroup>

</Project>
